# Integer formats
int1 = +99
int2 = -17
int3 = 1_000_000
hex = 0xDEADBEEF
oct = 0o755
bin = 0b11010110

# Floats
flt1 = +1.0
flt2 = 3.1415
flt3 = -0.01
flt4 = 5e+22
flt5 = 1e06
flt6 = -2E-2
flt7 = 6.626e-34
inf1 = inf
inf2 = -inf
nan = nan

# Booleans
bool1 = true
bool2 = false
